export const countryOption = [
    <option key="0" value="ALBANIA">ALBANIA</option>,
    <option key="1" value="ALGERIA">ALGERIA</option>,
    <option key="2" value="ANDORRA">ANDORRA</option>,
    <option key="3" value="ANGOLA">ANGOLA</option>,
    <option key="4" value="ANTIGUA AND BARBUDA">ANTIGUA AND BARBUDA</option>,
    <option key="5" value="ARGENTINA">ARGENTINA</option>,
    <option key="6" value="ARMENIA">ARMENIA</option>,
    <option key="7" value="AUSTRALIA">AUSTRALIA</option>,
    <option key="8" value="AUSTRIA">AUSTRIA</option>,
    <option key="9" value="AZERBAIJAN">AZERBAIJAN</option>,
    <option key="10" value="BAHAMAS">BAHAMAS</option>,
    <option key="11" value="BAHRAIN">BAHRAIN</option>,
    <option key="12" value="BANGLADESH">BANGLADESH</option>,
    <option key="13" value="BARBADOS">BARBADOS</option>,
    <option key="14" value="BELARUS">BELARUS</option>,
    <option key="15" value="BELGIUM">BELGIUM</option>,
    <option key="16" value="BELIZE">BELIZE</option>,
    <option key="17" value="BENIN">BENIN</option>,
    <option key="18" value="BHUTAN">BHUTAN</option>,
    <option key="19" value="BOLIVIA">BOLIVIA</option>,
    <option key="20" value="BOSNIA AND HERZEGOVINA">BOSNIA AND HERZEGOVINA</option>,
    <option key="21" value="BOTSWANA">BOTSWANA</option>,
    <option key="22" value="BRAZIL">BRAZIL</option>,
    <option key="23" value="BRUNEI">BRUNEI</option>,
    <option key="24" value="BULGARIA">BULGARIA</option>,
    <option key="25" value="BURKINA FASO">BURKINA FASO</option>,
    <option key="26" value="BURUNDI">BURUNDI</option>,
    <option key="27" value="CAMBODIA">CAMBODIA</option>,
    <option key="28" value="CAMEROON">CAMEROON</option>,
    <option key="29" value="CANADA">CANADA</option>,
    <option key="30" value="CAPE VERDE">CAPE VERDE</option>,
    <option key="31" value="CENTRAL AFRICAN REPUBLIC">CENTRAL AFRICAN REPUBLIC</option>,
    <option key="32" value="CHAD">CHAD</option>,
    <option key="33" value="CHILE">CHILE</option>,
    <option key="34" value="CHINA">CHINA</option>,
    <option key="35" value="COLOMBIA">COLOMBIA</option>,
    <option key="36" value="COMOROS">COMOROS</option>,
    <option key="37" value="CONGO, DEMOCRATIC REPUBLIC OF THE">CONGO, DEMOCRATIC REPUBLIC OF THE</option>,
    <option key="38" value="CONGO, REPUBLIC OF THE">CONGO, REPUBLIC OF THE</option>,
    <option key="39" value="COSTA RICA">COSTA RICA</option>,
    <option key="40" value="COTE D&apos;IVOIRE">COTE D&apos;IVOIRE</option>,
    <option key="41" value="CROATIA">CROATIA</option>,
    <option key="42" value="CUBA">CUBA</option>,
    <option key="43" value="CYPRUS">CYPRUS</option>,
    <option key="44" value="CZECH REPUBLIC">CZECH REPUBLIC</option>,
    <option key="45" value="DENMARK">DENMARK</option>,
    <option key="46" value="DJIBOUTI">DJIBOUTI</option>,
    <option key="47" value="DOMINICA">DOMINICA</option>,
    <option key="48" value="DOMINICAN REPUBLIC">DOMINICAN REPUBLIC</option>,
    <option key="49" value="ECUADOR">ECUADOR</option>,
    <option key="50" value="EGYPT">EGYPT</option>,
    <option key="51" value="EL SALVADOR">EL SALVADOR</option>,
    <option key="52" value="EQUATORIAL GUINEA">EQUATORIAL GUINEA</option>,
    <option key="53" value="ERITREA">ERITREA</option>,
    <option key="54" value="ESTONIA">ESTONIA</option>,
    <option key="55" value="ESWATINI">ESWATINI</option>,
    <option key="56" value="ETHIOPIA">ETHIOPIA</option>,
    <option key="57" value="FIJI">FIJI</option>,
    <option key="58" value="FINLAND">FINLAND</option>,
    <option key="59" value="FRANCE">FRANCE</option>,
    <option key="60" value="GABON">GABON</option>,
    <option key="61" value="GAMBIA">GAMBIA</option>,
    <option key="62" value="GEORGIA">GEORGIA</option>,
    <option key="63" value="GERMANY">GERMANY</option>,
    <option key="64" value="GHANA">GHANA</option>,
    <option key="65" value="GREECE">GREECE</option>,
    <option key="66" value="GRENADA">GRENADA</option>,
    <option key="67" value="GUATEMALA">GUATEMALA</option>,
    <option key="68" value="GUINEA">GUINEA</option>,
    <option key="69" value="GUINEA-BISSAU">GUINEA-BISSAU</option>,
    <option key="70" value="GUYANA">GUYANA</option>,
    <option key="71" value="HAITI">HAITI</option>,
    <option key="72" value="HONDURAS">HONDURAS</option>,
    <option key="73" value="HUNGARY">HUNGARY</option>,
    <option key="74" value="ICELAND">ICELAND</option>,
    <option key="75" value="INDIA">INDIA</option>,
    <option key="76" value="INDONESIA">INDONESIA</option>,
    <option key="77" value="IRAN">IRAN</option>,
    <option key="78" value="IRAQ">IRAQ</option>,
    <option key="79" value="IRELAND">IRELAND</option>,
    <option key="80" value="ISRAEL">ISRAEL</option>,
    <option key="81" value="ITALY">ITALY</option>,
    <option key="82" value="JAMAICA">JAMAICA</option>,
    <option key="83" value="JAPAN">JAPAN</option>,
    <option key="84" value="JORDAN">JORDAN</option>,
    <option key="85" value="KAZAKHSTAN">KAZAKHSTAN</option>,
    <option key="86" value="KENYA">KENYA</option>,
    <option key="87" value="KIRIBATI">KIRIBATI</option>,
    <option key="88" value="KOREA, DEMOCRATIC PEOPLE&apos;S REPUBLIC OF">KOREA, DEMOCRATIC PEOPLE&apos;S REPUBLIC OF</option>,
    <option key="89" value="KOREA, REPUBLIC OF">KOREA, REPUBLIC OF</option>,
    <option key="90" value="KOSOVO">KOSOVO</option>,
    <option key="91" value="KUWAIT">KUWAIT</option>,
    <option key="92" value="KYRGYZSTAN">KYRGYZSTAN</option>,
    <option key="93" value="LAO PEOPLE&apos;S DEMOCRATIC REPUBLIC">LAO PEOPLE&apos;S DEMOCRATIC REPUBLIC</option>,
    <option key="94" value="LATVIA">LATVIA</option>,
    <option key="95" value="LEBANON">LEBANON</option>,
    <option key="96" value="LESOTHO">LESOTHO</option>,
    <option key="97" value="LIBERIA">LIBERIA</option>,
    <option key="98" value="LIBYA">LIBYA</option>,
    <option key="99" value="LIECHTENSTEIN">LIECHTENSTEIN</option>,
    <option key="100" value="LITHUANIA">LITHUANIA</option>,
    <option key="101" value="LUXEMBOURG">LUXEMBOURG</option>,
    <option key="102" value="MADAGASCAR">MADAGASCAR</option>,
    <option key="103" value="MALAWI">MALAWI</option>,
    <option key="104" value="MALAYSIA">MALAYSIA</option>,
    <option key="105" value="MALDIVES">MALDIVES</option>,
    <option key="106" value="MALI">MALI</option>,
    <option key="107" value="MALTA">MALTA</option>,
    <option key="108" value="MARSHALL ISLANDS">MARSHALL ISLANDS</option>,
    <option key="109" value="MAURITANIA">MAURITANIA</option>,
    <option key="110" value="MAURITIUS">MAURITIUS</option>,
    <option key="111" value="MEXICO">MEXICO</option>,
    <option key="112" value="MICRONESIA">MICRONESIA</option>,
    <option key="113" value="MOLDOVA">MOLDOVA</option>,
    <option key="114" value="MONACO">MONACO</option>,
    <option key="115" value="MONGOLIA">MONGOLIA</option>,
    <option key="116" value="MONTENEGRO">MONTENEGRO</option>,
    <option key="117" value="MOROCCO">MOROCCO</option>,
    <option key="118" value="MOZAMBIQUE">MOZAMBIQUE</option>,
    <option key="119" value="MYANMAR">MYANMAR</option>,
    <option key="120" value="NAMIBIA">NAMIBIA</option>,
    <option key="121" value="NAURU">NAURU</option>,
    <option key="122" value="NEPAL">NEPAL</option>,
    <option key="123" value="NETHERLANDS">NETHERLANDS</option>,
    <option key="124" value="NEW ZEALAND">NEW ZEALAND</option>,
    <option key="125" value="NICARAGUA">NICARAGUA</option>,
    <option key="126" value="NIGER">NIGER</option>,
    <option key="127" value="NIGERIA">NIGERIA</option>,
    <option key="128" value="NORTH MACEDONIA">NORTH MACEDONIA</option>,
    <option key="129" value="NORWAY">NORWAY</option>,
    <option key="130" value="OMAN">OMAN</option>,
    <option key="131" value="PAKISTAN">PAKISTAN</option>,
    <option key="132" value="PALAU">PALAU</option>,
    <option key="133" value="PANAMA">PANAMA</option>,
    <option key="134" value="PAPUA NEW GUINEA">PAPUA NEW GUINEA</option>,
    <option key="135" value="PARAGUAY">PARAGUAY</option>,
    <option key="136" value="PERU">PERU</option>,
    <option key="137" value="PHILIPPINES">PHILIPPINES</option>,
    <option key="138" value="POLAND">POLAND</option>,
    <option key="139" value="PORTUGAL">PORTUGAL</option>,
    <option key="140" value="QATAR">QATAR</option>,
    <option key="141" value="ROMANIA">ROMANIA</option>,
    <option key="142" value="RUSSIA">RUSSIA</option>,
    <option key="143" value="RWANDA">RWANDA</option>,
    <option key="144" value="SAINT KITTS AND NEVIS">SAINT KITTS AND NEVIS</option>,
    <option key="145" value="SAINT LUCIA">SAINT LUCIA</option>,
    <option key="146" value="SAINT VINCENT AND THE GRENADINES">SAINT VINCENT AND THE GRENADINES</option>,
    <option key="147" value="SAMOA">SAMOA</option>,
    <option key="148" value="SAN MARINO">SAN MARINO</option>,
    <option key="149" value="SAO TOME AND PRINCIPE">SAO TOME AND PRINCIPE</option>,
    <option key="150" value="SAUDI ARABIA">SAUDI ARABIA</option>,
    <option key="151" value="SENEGAL">SENEGAL</option>,
    <option key="152" value="SERBIA">SERBIA</option>,
    <option key="153" value="SEYCHELLES">SEYCHELLES</option>,
    <option key="154" value="SIERRA LEONE">SIERRA LEONE</option>,
    <option key="155" value="SINGAPORE">SINGAPORE</option>,
    <option key="156" value="SLOVAKIA">SLOVAKIA</option>,
    <option key="157" value="SLOVENIA">SLOVENIA</option>,
    <option key="158" value="SOLOMON ISLANDS">SOLOMON ISLANDS</option>,
    <option key="159" value="SOMALIA">SOMALIA</option>,
    <option key="160" value="SOUTH AFRICA">SOUTH AFRICA</option>,
    <option key="161" value="SOUTH SUDAN">SOUTH SUDAN</option>,
    <option key="162" value="SPAIN">SPAIN</option>,
    <option key="163" value="SRI LANKA">SRI LANKA</option>,
    <option key="164" value="SUDAN">SUDAN</option>,
    <option key="165" value="SURINAME">SURINAME</option>,
    <option key="166" value="SWEDEN">SWEDEN</option>,
    <option key="167" value="SWITZERLAND">SWITZERLAND</option>,
    <option key="168" value="SYRIA">SYRIA</option>,
    <option key="169" value="TAIWAN">TAIWAN</option>,
    <option key="170" value="TAJIKISTAN">TAJIKISTAN</option>,
    <option key="171" value="TANZANIA">TANZANIA</option>,
    <option key="172" value="THAILAND">THAILAND</option>,
    <option key="173" value="TIMOR-LESTE">TIMOR-LESTE</option>,
    <option key="174" value="TOGO">TOGO</option>,
    <option key="175" value="TONGA">TONGA</option>,
    <option key="176" value="TRINIDAD AND TOBAGO">TRINIDAD AND TOBAGO</option>,
    <option key="177" value="TUNISIA">TUNISIA</option>,
    <option key="178" value="TURKEY">TURKEY</option>,
    <option key="179" value="TURKMENISTAN">TURKMENISTAN</option>,
    <option key="180" value="TUVALU">TUVALU</option>,
    <option key="181" value="UGANDA">UGANDA</option>,
    <option key="182" value="UKRAINE">UKRAINE</option>,
    <option key="183" value="UNITED ARAB EMIRATES">UNITED ARAB EMIRATES</option>,
    <option key="184" value="UNITED KINGDOM">UNITED KINGDOM</option>,
    <option key="185" value="UNITED STATES OF AMERICA">UNITED STATES OF AMERICA</option>,
    <option key="186" value="URUGUAY">URUGUAY</option>,
    <option key="187" value="UZBEKISTAN">UZBEKISTAN</option>,
    <option key="188" value="VANUATU">VANUATU</option>,
    <option key="189" value="VENEZUELA">VENEZUELA</option>,
    <option key="190" value="VIETNAM">VIETNAM</option>,
    <option key="191" value="YEMEN">YEMEN</option>,
    <option key="192" value="ZAMBIA">ZAMBIA</option>,
    <option key="193" value="ZIMBABWE">ZIMBABWE</option>,
]

export default countryOption;